import time
from io import BytesIO


def generate_markdown_report(company_name: str, data: dict) -> str:
    ts = time.strftime("%B %d, %Y at %H:%M")
    return f"""# AI Intelligence Report: {company_name}
*Generated on {ts}*

---

## 1. Company Overview
{data.get('overview', '')}

---

## 2. Key Business Information
{data.get('biz_info', '')}

---

## 3. Potential Business Challenges
{data.get('challenges', '')}

---

## 4. AI Opportunities
{data.get('ai_opps', '')}

---

## 5. Personalized CEO Pitch
{data.get('pitch', '')}

---
*Generated by AI Research Agent · Powered by Groq + DuckDuckGo*
"""


def generate_pdf_report(company_name: str, data: dict) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_s = ParagraphStyle("T", parent=styles["Title"], fontSize=20,
                              textColor=colors.HexColor("#1e3a5f"), spaceAfter=4)
    sub_s   = ParagraphStyle("S", parent=styles["Normal"], fontSize=10,
                              textColor=colors.HexColor("#6c757d"), spaceAfter=16)
    head_s  = ParagraphStyle("H", parent=styles["Heading2"], fontSize=13,
                              textColor=colors.HexColor("#0d6efd"), spaceBefore=14, spaceAfter=6)
    body_s  = ParagraphStyle("B", parent=styles["Normal"], fontSize=11,
                              leading=16, spaceAfter=6, textColor=colors.HexColor("#212529"))

    story = [
        Paragraph(f"AI Intelligence Report", title_s),
        Paragraph(company_name, ParagraphStyle("CN", parent=styles["Title"], fontSize=16,
                  textColor=colors.HexColor("#0d6efd"), spaceAfter=4)),
        Paragraph(f"Generated on {time.strftime('%B %d, %Y')}", sub_s),
        HRFlowable(width="100%", thickness=2, color=colors.HexColor("#0d6efd")),
        Spacer(1, 12),
    ]

    sections = [
        ("1. Company Overview",             data.get("overview", "")),
        ("2. Key Business Information",     data.get("biz_info", "")),
        ("3. Potential Business Challenges",data.get("challenges", "")),
        ("4. AI Opportunities",             data.get("ai_opps", "")),
        ("5. Personalized CEO Pitch",       data.get("pitch", "")),
    ]

    for heading, content in sections:
        story.append(Paragraph(heading, head_s))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dee2e6")))
        story.append(Spacer(1, 4))
        for line in content.split("\n"):
            line = line.strip()
            if line:
                safe = line.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
                story.append(Paragraph(safe, body_s))
        story.append(Spacer(1, 8))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by AI Research Agent · Powered by Groq + DuckDuckGo",
        ParagraphStyle("F", parent=styles["Normal"], fontSize=9,
                       textColor=colors.HexColor("#6c757d"), alignment=1)
    ))

    doc.build(story)
    return buffer.getvalue()
